### ISSUE TITLE
No_Keyboard_Beta.hex

### ISSUE THREAD

**Issue by thalesfsp** [Morningstar-Engineering/MC6-PRO-MIDI-Controller#1]
What "No_Keyboard" means? Thank you

**Comment by Ziggytar** [comment]
That would interest me too!

**Comment by thalesfsp** [comment]
@Ziggytar since Nov 23, 2023 and counting. 

ccL @tyzjames

**Comment by tyzjames** [comment]
Sorry, I missed this. It just means that the USB interface only exposes a MIDI interface and no keyboard interface. The standard firmware exposes a USB MIDI and Keyboard interface. 

## So when should you use the No_Keyboard firmware?
1. When you plan to connect it to an iOS device via cable. If the iOS device detects that a keyboard is connected, the iOS device will not display the onscreen keyboard.
2. When you have trouble connecting to other USB Host interfaces like the iConnectivity mioXM. These USB Host devices oly accept USB MIDI interfaces, and will not work with MIDI + Keyboard.

## What are the differences between the standard and no_keyboard firmware?
1. USB Interface implementation, as explained above
2. With the No_keyboard firmware, you cannot use the Keystrokes message type since there is no USB Keyboard interface implemented.
